/* eslint-disable @typescript-eslint/no-unused-vars */
/* eslint-disable react/react-in-jsx-scope */
import type { Metadata } from "next"
import { Inter } from "next/font/google"
import "./../globals.css"
import AdminSideMenuAndHeader from "@/components/organisms/adminSideMenuAndHeader"
import { ApolloProviderClientWrapper } from "@/components/providers/apolloProviderClientWrapper"
import { AdminAuthWrapper } from "@/components/organisms/adminAuthWrapper"
import { RecoilProvider } from "@/components/providers/recoilProvider"

const inter = Inter({ subsets: ["latin"] })

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <RecoilProvider>
      <ApolloProviderClientWrapper>
        <AdminSideMenuAndHeader />
        <AdminAuthWrapper>{children}</AdminAuthWrapper>
      </ApolloProviderClientWrapper>
    </RecoilProvider>
  )
}
