import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './../globals.css'
import Header from '@/components/header/header'
import AdminSideMenuAndHeader from '@/components/sideMenu/adminSideMenuAndHeader'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="ja">
      <body className={inter.className}>
        <AdminSideMenuAndHeader />
        {children}
      </body>
    </html>
  )
}
